"""Rate limit, firstblood, po, and pools

Revision ID: 00000000000
Revises: 4fe3eeed9a9d
Create Date: 2024-11-14 19:57:37.410152

"""
from alembic import op  # noqa: I001
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00000000000"
down_revision = "4fe3eeed9a9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("challenges", sa.Column("rate_limit_buffer", sa.Integer, default=-1))
    op.add_column("challenges", sa.Column("rate_limit_span", sa.Integer, default=-1))

    op.add_column("challenges", sa.Column("had_first_blood", sa.Boolean, default=False))
    op.add_column("challenges", sa.Column("po_visiblity", sa.Boolean, default=True))

    op.add_column("users", sa.Column("pool", sa.String(80)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("challenges", "rate_limit_buffer")
    op.drop_column("challenges", "rate_limit_span")

    op.drop_column("challenges", "had_first_blood")
    op.drop_column("challenges", "po_visiblity")

    op.drop_column("users", "pool")
    # ### end Alembic commands ###
